Repository SODALITE-EU/xopera-rest-api, pull requests merged in 2021-02, with the labels that each got.

#69 Outputs and validate commands
  openapi-spec.yml
  src/opera/api/blueprint_converters/blueprint2CSAR.py
  src/opera/api/cli.py
  src/opera/api/controllers/background_invocation.py
  src/opera/api/controllers/deploy_controller.py
  src/opera/api/controllers/diff_controller.py
  src/opera/api/controllers/info_controller.py
  src/opera/api/controllers/manage_controller.py
  src/opera/api/controllers/outputs_controller.py
  src/opera/api/controllers/undeploy_controller.py
  src/opera/api/controllers/update_controller.py
  src/opera/api/controllers/validate_controller.py
  src/opera/api/gitCsarDB/main.py
  src/opera/api/service/csardb_service.py
  src/opera/api/service/sqldb_service.py
  src/opera/api/tests/test_03_gitCsarDB.py
  src/opera/api/tests/test_14_validate.py
  src/opera/api/tests/test_15_outputs.py
  src/opera/api/util/xopera_util.py
Labels: feature

#70 Auth integration
  openapi-spec.yml
  src/opera/api/blueprint_converters/blueprint2CSAR.py
  src/opera/api/cli.py
  src/opera/api/controllers/background_invocation.py
  src/opera/api/controllers/deploy_controller.py
  src/opera/api/controllers/diff_controller.py
  src/opera/api/controllers/info_controller.py
  src/opera/api/controllers/manage_controller.py
  src/opera/api/controllers/outputs_controller.py
  src/opera/api/controllers/security_controller.py
  src/opera/api/controllers/undeploy_controller.py
  src/opera/api/controllers/update_controller.py
  src/opera/api/controllers/validate_controller.py
  src/opera/api/gitCsarDB/connectors.py
  src/opera/api/gitCsarDB/tag_util.py
  src/opera/api/service/sqldb_service.py
  src/opera/api/settings/settings.py
  src/opera/api/tests/conftest.py
  src/opera/api/tests/test_01_MockConnector.py
  src/opera/api/tests/test_05_blueprint2CSAR.py
  src/opera/api/tests/test_06_util.py
  src/opera/api/tests/test_08_info.py
  src/opera/api/tests/test_09_manage.py
  src/opera/api/tests/test_12_diff.py
  src/opera/api/tests/test_13_update.py
  src/opera/api/tests/test_15_outputs.py
  src/opera/api/tests/test_16_security.py
  src/opera/api/util/xopera_util.py
Labels: enhancement, feature

#71 API refractor
  .gitignore
  Dockerfile
  README.md
  api-calls.http
  docker-compose.yml
  openapi-spec.yml
  requirements.txt
  src/opera/api/blueprint_converters/blueprint2CSAR.py
  src/opera/api/controllers/background_invocation.py
  src/opera/api/controllers/blueprint_controller.py
  src/opera/api/controllers/deploy_controller.py
  src/opera/api/controllers/deployment_controller.py
  src/opera/api/controllers/diff_controller.py
  src/opera/api/controllers/info_controller.py
  src/opera/api/controllers/manage_controller.py
  src/opera/api/controllers/outputs_controller.py
  src/opera/api/controllers/security_controller.py
  src/opera/api/controllers/ssh_controller.py
  src/opera/api/controllers/undeploy_controller.py
  src/opera/api/controllers/update_controller.py
  src/opera/api/controllers/validate_controller.py
  src/opera/api/gitCsarDB/connectors.py
  src/opera/api/gitCsarDB/main.py
  src/opera/api/service/csardb_service.py
  src/opera/api/service/sqldb_service.py
  src/opera/api/settings/settings.py
  src/opera/api/tests/conftest.py
  src/opera/api/tests/test_01_MockConnector.py
  src/opera/api/tests/test_03_gitCsarDB.py
  src/opera/api/tests/test_04_sqldb.py
  src/opera/api/tests/test_07_ssh.py
  src/opera/api/tests/test_08_info.py
  src/opera/api/tests/test_09_blueprint.py
  src/opera/api/tests/test_09_manage.py
  src/opera/api/tests/test_10_deploy.py
  src/opera/api/tests/test_10_deployment.py
  src/opera/api/tests/test_11_undeploy.py
  src/opera/api/tests/test_12_diff.py
  src/opera/api/tests/test_13_update.py
  src/opera/api/tests/test_14_validate.py
  src/opera/api/tests/test_15_outputs.py
  src/opera/api/util/file_util.py
  src/opera/api/util/git_util.py
  src/opera/api/util/xopera_util.py
Labels: bugfix, enhancement, feature, major

#80 Check if blueprint is still in use before deleting it
  src/opera/api/controllers/blueprint_controller.py
  src/opera/api/service/sqldb_service.py
  src/opera/api/tests/test_04_sqldb.py
  src/opera/api/tests/test_09_blueprint.py
  src/opera/api/util/file_util.py
Labels: feature

#83 Update HTTP status codes
  openapi-spec.yml
  src/opera/api/controllers/blueprint_controller.py
  src/opera/api/controllers/deployment_controller.py
  src/opera/api/tests/test_09_blueprint.py
  src/opera/api/tests/test_10_deployment.py
Labels: bugfix
