Repository SODALITE-EU/xopera-rest-api, pull requests merged in 2021-04, with the labels that each got.

#94 Added Jenkins configuration for Vault
  Jenkinsfile
  xOpera-rest-blueprint/inputs/input.yaml.tmpl
Labels: bugfix

#95 Instance state and current stdout in Invocation object
  docker-compose.yml
  src/opera/api/controllers/background_invocation.py
  xOpera-rest-blueprint/inputs/input.yaml.tmpl
  xOpera-rest-blueprint/service.yaml
Labels: feature, minor

#96 Support multiple concurrent orchestration jobs
  Jenkinsfile
  docker-compose.yml
  src/opera/api/controllers/background_invocation.py
  src/opera/api/controllers/deployment_controller.py
  src/opera/api/settings/settings.py
  src/opera/api/util/xopera_util.py
  xOpera-rest-blueprint/inputs/input.yaml.tmpl
Labels: feature, minor

#99 Add ParseError location
  src/opera/api/controllers/background_invocation.py
Labels: bugfix

#101 Fix /update and /diff endpoints
  src/opera/api/controllers/background_invocation.py
  src/opera/api/service/sqldb_service.py
Labels: bugfix, patch
